package root.levels;

public enum ActorNames 
{
	AAGUN,
	BOMB_FLINGER,
	SAM,
	SMART_AAGUN,
	BOMBER,
	BOMB_ONLY_BOMBER,
	JET,
	MISSLE_JET,
	SINE_WAVE_BOMBER,
	SMART_JET,
	TARGET_PLANE,
	WAVE_JET,
	FLAK_GUN,
	SMART_FLAK_GUN,
	SHOTGUN_JET,
	FLAK_JET,
	FLAK_SHOTGUN_JET,
	SHOTGUN_FLAK_GUN,
	SHOTGUN_AAGUN,
	SMART_SHOTGUN_AAGUN,
	SMART_SHOTGUN_FLAK_GUN,
	SMART_SHOTGUN_JET,
	SMART_SHOTGUN_FLAK_JET,
	SMART_FLAK_JET,
	PT_BOAT
}
